/**
 * Helpers for auto-generated entity descriptions.
 *
 * Discovery produces entities from static analysis only, so their description
 * cannot claim business meaning. The generated text still carries the evidence
 * that produced the candidate, which the previous bare template did not.
 */

/** Prefix marking a description generated by discovery (no business semantics yet). */
export const SKELETON_DESCRIPTION_PREFIX = 'Auto-discovered candidate ';

/** Prefix used by earlier versions, still present in knowledge files written before this change. */
export const LEGACY_SKELETON_DESCRIPTION_PREFIX = 'Discovered business candidate: ';

/** Prefix used for entities derived from a SQL table definition. */
export const SQL_TABLE_DESCRIPTION_PREFIX = 'Discovered from SQL table ';

const MAX_EVIDENCE_IN_DESCRIPTION = 3;

/**
 * Build an evidence-carrying description for an auto-discovered entity.
 * Keeps the same machine-readable prefix so downstream code can still tell
 * "generated" descriptions from human/LLM authored ones.
 */
export function skeletonDescription(name: string, evidence: string[] = []): string {
  const files = evidence.filter(Boolean).slice(0, MAX_EVIDENCE_IN_DESCRIPTION);
  const location = files.length
    ? `; evidence: ${files.join(', ')}`
    : '; no file-level evidence captured (name-only match)';
  return `${SKELETON_DESCRIPTION_PREFIX}${name}${location}. Confirm the business meaning before promoting.`;
}

/** True when the description was generated by discovery and carries no business semantics. */
export function isSkeletonDescription(description: string | undefined): boolean {
  if (!description) return false;
  return (
    description.startsWith(SKELETON_DESCRIPTION_PREFIX) || description.startsWith(LEGACY_SKELETON_DESCRIPTION_PREFIX)
  );
}

/** True when the entity was derived from a SQL table definition. */
export function isSqlTableDescription(description: string | undefined): boolean {
  if (!description) return false;
  return description.startsWith(SQL_TABLE_DESCRIPTION_PREFIX);
}
